name: Fetch News Daily

on:
  schedule:
    - cron: "30 6 * * *"  # Runs at 6:30 AM UTC (12:00 PM IST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install feedparser

      - name: Run Fetch Script
        run: python news.py  # This runs your Python script

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "Updated news.json"
          git push
