name: Fetch News and Update JSON

on:
  schedule:
    - cron: "29 17 * * *" # Runs at 06:30 UTC daily
  workflow_dispatch: # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions: write-all # ✅ Ensure GitHub Actions has write access
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # ✅ Use token with write access

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests bs4 feedparser # ✅ Install required dependencies

      - name: Run News Scraper
        run: python scraper/news.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "Auto-update news.json" || echo "No changes to commit"
          git push origin main  # ✅ Ensure correct push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
