name: Fetch News and Update JSON

on:
  schedule:
    - cron: "30 6 * * *" # Runs at 06:00 UTC daily (Change as needed)
  workflow_dispatch: # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests bs4 # Install necessary Python packages

      - name: Run News Scraper
        run: python scraper/news.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add backend/news.json
          git commit -m "Auto-update news.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
